const aiStatements = [
  "Golf is a strange little battle between patience and a tiny white ball that refuses to cooperate. One minute you feel like a professional, and the next you're searching through bushes wondering where everything went wrong.",
  "Seattle is a vibrant Pacific Northwest metropolis famous for its iconic Space Needle and bustling Pike Place Market. Surrounded by mountain ranges and the waters of Puget Sound, the city seamlessly blends urban living with stunning natural landscapes. It is globally recognized as a powerhouse for technological innovation, home to corporate giants like Amazon and the birthplace of Starbucks.",
  "Money is a medium of exchange that allows people to trade goods and services without relying on direct bartering. Beyond its practical function, money often carries emotional weight, shaping people's sense of security, freedom, and self-worth. How a person manages money - saving, spending, investing - can have a lasting impact on their long-term stability and opportunities.",
  "Weight lifting is a highly effective form of strength training that utilizes free weights, machines, or resistance bands to build muscle mass and increase bone density. By progressively challenging muscles through structured movements like squats, deadlifts, and presses, individuals can significantly boost their metabolic rate and physical endurance. Beyond physical changes, a consistent routine enhances joint stability, improves posture, and offers substantial benefits for mental health and focus.",
  "Arizona is a southwest desert state famous for its breathtaking geological formations, most notably the massive and vibrant Grand Canyon. The region features a unique contrast of sun-drenched landscapes populated by giant Saguaro cacti and cooler, high-altitude pine forests surrounding towns like Flagstaff. It boasts a rich cultural history alongside booming urban centers like Phoenix, making it a major destination for outdoor adventurers and winter residents alike.",
  "After watching Bicycle Thieves for my College Writing Program 201 class, I came away loving the film and would rank it among my favorites. Bicycle Thieves is a masterpiece of Italian Neorealism directed by Vittorio De Sica that follows a desperate father searching postwar Rome for his stolen bicycle, which he needs to keep his job. Filmed on location using non-professional actors, the movie offers a raw and heartbreaking critique of poverty, unemployment, and systemic indifference. It is widely considered one of the greatest films in cinematic history, celebrated for its emotional depth and its profound exploration of the bond between a father and his young son.",
  "A comprehensive weight loss program blends a structured, calorie-controlled nutrition plan with regular cardiovascular and strength-training exercises to ensure sustainable lifestyle habits. Rather than promoting extreme restrictions, successful programs focus on behavioral modifications, portion control, and accountability to foster a healthy relationship with food. Over time, these structured routines not only reduce body fat but also improve cardiovascular health, boost energy levels, and lower the risk of chronic metabolic conditions.",
  "Surfing is an exhilarating water sport where an individual rides the forward face of a moving wave, typically using a specially designed surfboard to glide across the water. Originating as a deeply spiritual practice in ancient Polynesia, it has evolved into a global phenomenon and an Olympic sport celebrated for its unique subculture and connection to nature. Beyond the physical demands of balance, core strength, and cardiovascular endurance, it offers participants a powerful mental escape driven by the rhythm of the ocean.",
  "The Kepler Space Telescope was a NASA mission that revolutionized our understanding of planetary systems beyond our own. Launched in 2009 and named after the 17th-century astronomer Johannes Kepler, the spacecraft was designed to search for Earth-sized exoplanets orbiting distant stars within their habitable zones. Using the transit method - detecting the slight dimming of a star's light as a planet passes in front of it - Kepler observed over 150,000 stars during its nearly decade-long mission. The mission was extraordinarily successful, discovering more than 2,600 confirmed exoplanets and fundamentally transforming our knowledge of planetary diversity in the universe. After running out of fuel, Kepler was retired in 2018, but its legacy continues as scientists analyze the vast dataset it collected and as it paved the way for future exoplanet-hunting missions like the James Webb Space Telescope.",
  "Formula One (F1) is the highest class of international single-seater motor racing, featuring drivers competing in high-performance cars on circuits around the world. The sport is organized by the Federation Internationale de l'Automobile (FIA), which sets the rules and oversees the championship. Drivers and teams compete throughout a season, earning points based on their finishing positions to determine the World Drivers' and Constructors' Champions. F1 is known for its advanced technology, high speeds, and intense competition between teams such as Ferrari, Mercedes, and Red Bull Racing.",
  "Chemistry has become one of the subjects that I am most passionate about because it helps explain how the world works at a molecular level. Through my chemistry courses, I have enjoyed learning how different compounds interact, why reactions occur, and how small structural changes can completely change the properties of a molecule. Organic Chemistry especially stood out to me because I enjoyed understanding reaction mechanisms and seeing how molecules can be transformed in different ways. My interest in chemistry has continued to grow through both my classes and research experiences, and I hope to continue studying chemistry at a higher level in graduate school.",
  "About 87 years ago, our fathers started a new country on this land. They created it to be free and based on the belief that everyone is equal. Now we are in the middle of a major civil war that is testing whether this country, built on freedom and equality, can survive. We are gathered here on a battlefield where this war was fought. We have come to set aside part of this land as a final resting place for the people who died fighting to keep the country alive. It is right and important that we do this.",
  "If I had to pick a favorite soccer team, I would choose FC Barcelona. I like Barcelona because of their unique style of play, especially their focus on possession, creativity, and technical ability. Their history is also a major reason, with legendary players such as Lionel Messi, Xavi, Andres Iniesta, and Ronaldinho having all played for the club. Beyond the players, I think Barcelona's identity and commitment to developing young talent through La Masia make the club especially interesting to follow.",
  "Weight lifting plays a fundamental role in maintaining physical longevity, metabolic efficiency, and joint health across all life stages. Beyond driving muscle hypertrophy, resistance training increases bone mineral density to safeguard against age-related degeneration and fortifies connective tissues around high-stress joints like the knees, hips, and shoulders. From a physiological perspective, building lean tissue boosts basal metabolic rate and enhances insulin sensitivity, aiding in blood glucose regulation. Additionally, heavy multi-joint movements enhance motor unit recruitment and neuromuscular control, improving daily functional movement patterns while dampening chronic stress through positive central nervous system adaptations.",
  "Baseball is a sport where two teams take turns batting and fielding, trying to score more runs than the other team. A batter hits a ball thrown by the pitcher and runs around four bases to score a run. The fielding team tries to get batters out by catching the ball, tagging runners, or throwing the ball to a base before a runner reaches it.",
  "I think using AI for academic purposes in college can be helpful when it is used responsibly. AI can help students understand difficult topics, brainstorm ideas, organize information, and improve their writing. However, students should not rely on AI to complete their assignments for them because doing so can prevent them from developing important skills and may be considered academic dishonesty. Instead, AI should be used as a learning tool that supports students while they still do their own thinking and work. Overall, I believe AI can be a valuable part of college education as long as students use it honestly and follow their professors' guidelines.",
  "Partisan redistricting can be used to create districts that favor one party and help secure more votes or seats. This can disenfranchise voters by weakening the power of their individual votes and limiting meaningful political competition. As a result, extreme partisan redistricting can undermine democratic representation and is fundamentally undemocratic.",
  "Formula 1 is the highest level of international single-seater racing, featuring teams and drivers competing at circuits around the world. Each season consists of races called Grands Prix, where drivers compete for points toward the Drivers' and Constructors' Championships. F1 combines speed, strategy, engineering, and teamwork, making it one of the most competitive and globally popular sports.",
  "In contemporary Mexican social movements, maternal activism has transformed traditional motherhood into a powerful platform for public resistance against systemic violence and state impunity. Grassroots collectives of searching mothers, known as madres buscadoras, actively conduct independent physical searches for thousands of missing persons across deserts and clandestine graves. By staging massive protests and transforming traditional celebrations like Mother's Day into nationwide demonstrations, these activists continually pressure the government and redefine the struggle for human rights in Mexico.",
  "Metallica is an American heavy metal band formed in 1981, widely recognized as one of the pioneering \"Big Four\" of thrash metal alongside Megadeth, Slayer, and Anthrax. The band achieved massive global commercial success with the release of their self-titled 1991 album (The Black Album), which featured iconic anthems like \"Enter Sandman\" and \"Nothing Else Matters.\" Over a career spanning more than four decades, they have won nine Grammy Awards and remain one of the most influential and highest-selling rock acts in music history.",
];

const realStatements = [
  "I chose to write about Golf. I love playing golf, it takes my mind off the real world. I am a 3.2 handicap now, which is very good.",
  "It is best to go to Seattle during the summer when it is warm and you can explore the mountains. On a 3 day trip you should spend one day downtown, the next day take a trip to Bainbridge island and on the final day go to Mt. Rainier. While downtown explore Pike Place Market and grab lunch while shopping with views of the ocean. From there you can also explore West Seattle and Lincoln Park. The San Juan islands are also very unique to Seattle, taking a ferry to Bainbridge or Vashon gives you unique views of the Puget Sound. You can often see Orcas from the ferry ride. Finally, what makes Seattle so special is the mountains close by. From Paradise lodge at Mt. Rainier you get breathtaking views of the mountain regardless of if you want to hike or not. A weekend in Seattle in the summer gives you a taste of both the mountains and the city and will be filled with excellent adventures.",
  "Money's a strange thing, society basically revolves around it, almost worships it, even though at the end of the day it's just paper that grows on trees. Yet we spend so much of our lives chasing more of it, like it's the whole point instead of just a tool.It's so interesting that  something we invented ends up deciding so much about how we actually live.",
  "I've noticed recently that \"gym culture\" has blown up. Social media is probably the culprit for this as well as the ever changing beauty standards (not necessarily a good thing), but I can't say that the health trend of going to the gym is all that bad. As a kinesiology major, the importance of muscle and being in good physical health has been beaten into me class after class. Having enough muscle helps preserve strength into old age, consequently decreasing the risk of falls and injury. Similarly, it also protects autonomy and ensures you don't have to ask anyone for help using the bathroom or getting up from a chair as soon as you hit 80. Another very important benefit of weight lifting is the impact that it has on your bone density. Putting force onto your body help increase bone density and mineral content, ensuring that, especially for women once menopause it hit, we don't develop osteoporosis or unnecessary bone fractures.",
  "I live in Scottsdale, Arizona. Year round we have very nice weather, but in the summer it gets very hot. In the winter it usually has daytime highs around high 60s, with nighttime lows getting down into the low 40s and sometimes high 30s. However, in the summertime, it is usually daytime highs in the range of 103-110, with a few days a summer nearing 120. Nighttime lows are around the high 80s and low 90s. We get very little rain, this amount is usually around 8-10 inches per year and that includes summer monsoon season, when it can rain up to 3 inches in a span of 30 minutes.",
  "Recently, I watched the movie Bicycle Thieves for my class titled College Writing Program 201. I ultimately loved the film and thought it had a high rating on my list. Teenagers and adults might not see the movie as good because of the amount of dead space and pointless narrative there is in the movie. However, a lot of movies with critical acclaim do this today. I thought the movie was really great and it made me want to pursue more Victorio De Sicca movies. I thought it very interesting and inspiring that De Sicca chose actors and actresses that he found on the streets in Italy. I think that some people fail to understand his genius. How he moves the narrative away from the main character, that some scenes seem unrelated to the story, and that he doesn't give you a place or background on the story. While Antonio, the main character, is searching for his bike with his son, he changes a lot throughout the movie. Trying to enjoy simple pleasures before the next day since losing the bike essentially means he has no job. Or when he gets more and more frustrated which causes him to enter a state of confusion on if he'd like to press charges against the alleged thief. In the end, he sheds a tear as he forces himself to steal a bike unknowingly being watched by his son.",
  "Losing weight and losing fat are often interlinked, but extremely different. Losing weight means losing overall body weight, which can come from muscle, fat, water weight, and sometimes even bone density if done in an unhealthy way. Losing fat means keeping all other variables (usually muscle, mostly) constant. Losing either weight or fat requires a calorie deficit. However, losing fat while trying to preserve muscle not only requires a calorie deficit but also maintaining a high protein intake and consistent weightlifting.",
  "Surfing is a very fun activity becuase it lets you move with the ocean, turning back and forth with the push and pull of the tide. It can be very dangerous to surf big waves because of the force behind them and many people have died trying. I wish I went surfing more often, but the water in San Francisco is much colder than Souther California.",
  "In 2009, NASA launched the Kepler Space telescope to search for more Earth-sized planets in the Milky Way galaxy. It was designed to look for exoplanets using the transit method, searching for the slight dimming of a star when a planet passes in front of it. This mission is how scientists found the first confirmed planetary system with more than one planet orbiting the same star, which they called Kepler-9. Before this, humans didn't know of a single planet outside of our solar system, so the discovery of \"planets everywhere\" basically created an entire new way to explore and understand our galaxy. While it was originally positioned to stare continuously at 150,000 stars in the patch of sky in the Cygnus constellation, it was so successful that scientists decided to extend its mission and shift its point of view about every 3 months. This new leg of the mission was called K2, and used the pressure of sunlight to maintain its pointing after the original mechanism malfunctioned in 2013. Before being retired in 2018, it identified over 2,600 confirmed exoplanets in our galaxy, data which was made available to the public and has led and will continue to lead to many more scientific discoveries.",
  "Formula One is the most advanced form of international car racing. Formula One consists of races called Grand Prixs, which are held in numerous countries around the world. There are two World Championships within Formula One, one for drivers and one for constructors (teams). The most recent drivers' champion was Lando Norris, and the most recent constructors' champion was the McLaren F1 team.",
  "Chemistry is an incredible subject. I have really enjoyed learning about all of the different reactions and forms of chemistry in all of the chemistry classes I have taken. I specifically really enjoyed Organic Chemistry, and post grad I want to get a PhD in that subject.",
  "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal.  Now we are engaged in a great civil war, testing whether that nation, or any nation so conceived and so dedicated, can long endure. We are met on a great battle-field of that war. We have come to dedicate a portion of that field, as a final resting place for those who here gave their lives that that nation might live. It is altogether fitting and proper that we should do this.",
  "For me, choosing a team never involves counting how many trophies they have in the trophy room. I have supported the Houston Rockets through seasons when even a well-rounded roster could not make it past the first or second round of the playoffs, and through years when they were among the worst teams in the NBA. Regarding football, I have supported Brazil's national team since 2018, when I watched my first World Cup with my family. For me, neither of these began because I counted which team had the most trophies or because I went on Kalshi and checked who had the highest chance of winning. So when I decided Real Madrid was my favorite club, their trophies didn't convince me; my sense of belonging did. I never pick teams based on accolades. For me, that sense of belonging came from players like Vinicius Jr., the rivalries I dragged myself into, and the Brazilian connection that felt familiar to me.",
  "I've noticed recently that \"gym culture\" has blown up. Social media is probably the culprit for this as well as the ever changing beauty standards (not necessarily a good thing), but I can’t say that the health trend of going to the gym is all that bad. As a kinesiology major, the importance of muscle and being in good physical health has been beaten into me class after class. Having enough muscle helps preserve strength into old age, consequently decreasing the risk of falls and injury. Similarly, it also protects autonomy and ensures you don't have to ask anyone for help using the bathroom or getting up from a chair as soon as you hit 80. Another very important benefit of weight lifting is the impact that it has on your bone density. Putting force onto your body help increase bone density and mineral content, ensuring that, especially for women once menopause it hit, we don't develop osteoporosis or unnecessary bone fractures.",
  "Baseball is a popular sport where 9 innings are played and each team is on offense for half of an inning and defense for the other half of the inning. Each team uses pitchers who throw a baseball to hitters who try to hit the ball with a bat. A given team scored runs by hitting the ball where defenders aren't and advancing around the bases to cross home plate.",
  "I think that AI should be used in appropriate parts of the assignments. It should not be used to generate the whole answer or analyze the content, but it could be used to aid the students to better understand the prompt or the specific paper they are reading. It could also be used to generate the outline based on the idea that the students have, or help check grammatical issues. While there are benefits of AI usage in academic context, heavy reliance on AI could hinder the actual learning process. It could discourage students from utilizing their critical thinking skills when solving problems and limit their creativity. Thus, AI should be utilized only to an extent which can aid the students with the learning process, but not for completing the assignment totally based on AI or generating AI-based ideas.",
  "In 2026, we now live in a world where politicians choose their voters instead of the constituants. This is thanks to many states redistricting to garner votes favoring their party identities. While it seeks to \"balance\" the vote, it primarily disinfreanchises many americans from their right to vote thus swaying the nation farther from democracy.",
  "Formula 1 is a sport with 22 drivers and 11 teams who compete in 24 races per season for points. The team with the most points at the end of the season wins the Constructors' Championship, and the driver who finishes with the most points wins the Drivers' Championship. The reigning 2025 champion is 26-year-old Lando Norris, and the current 2026 championship leader is 19-year-old Kimi Antonelli.",
  "There exist two key generations of mother activism in contemporary Mexican social movements: the mothers of the disappeared (las donas) of leftist political activists from Mexico's \"Dirty War\" and the mothers of the disappeared (las madres buscadoras) from the \"War on Drugs.\" While there is a considerable amount of scholarship on the history and cultural phenomenon of mother activism in Latin America (particularly, Argentina's Mothers of the Plaza de Mayo of the 1970s), there is little scholarship on the mothers of the disappeared in Mexico's Dirty Wars. This chapter builds on critical mother activist studies by drawing parallels between this rich history of maternal social activism of Latin America's Dirty Wars and the mother-led collectives in Mexico searching for their disappeared children, from the 1970s to the present. Here, I will interrogate the various methods of insurgent mother activism, such as using public sites to stage maternal forms of resistance and protest, upon which both generations of mothers of the disappeared relied. These acts of public incivility to center their maternal rage and grief defied the state's notion of respectability politics and proper forms of mother activism, and it is important to delve into the various iterations of protest and maternal defiance.",
  "Fans and critics of Metallica, by far the best-selling metal band and one of the best-selling musical artists of all time, sometimes accuse the band of \"selling out\" - abandoning the style or values of metal in a cynical attempt to sell more records. Metallica began their career championing a new style called \"thrash metal\" that was faster, heavier, and louder than previous heavy metal. Aspects of the sell-out narrative first began to emerge in reactions to Metallica's ballads (starting with \"Fade to Black\" in 1984) which used acoustic or clean guitars and less aggressive vocal styles to depict feelings of frustration, powerlessness, and despair; but there was a much stronger backlash to the so-called \"Black Album,\" Metallica (1991).",
];

let realAnswer = null;

const questionElement = document.getElementById("question");
const optionsElement = document.getElementById("options");
const nextButton = document.getElementById("next");

nextButton.addEventListener("click", nextQuestion)

function getRandomInt(max) {
  return Math.floor(Math.random() * max);
}

function showQuestion() {
  optionsElement.innerHTML = "";

  let statements = [
    aiStatements[getRandomInt(aiStatements.length)],
    realStatements[getRandomInt(realStatements.length)]
  ];

  realAnswer = statements[1];

  if (getRandomInt(2) === 0) {
    console.log("switch")
    statements.reverse();
  }

  statements.forEach(option => {
    const button = document.createElement("button");
    button.innerText = option;
    optionsElement.appendChild(button);
    button.addEventListener("click", selectAnswer)
  });
}

function selectAnswer(e) {
  const selectedButton = e.target;

  let feedback = null;
  if (selectedButton.innerHTML === realAnswer) {
    feedback = "Correct, you selected the real statement";
  } else {
    feedback = "Wrong, you selected the AI statement";
  }

  optionsElement.innerHTML = `
    <p>${feedback}</p>
  `;

  realAnswer = null;
}

function nextQuestion(e) {
  showQuestion();
}

showQuestion();